learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Define padroẽs de URL para learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Pagina inicial
    path('', views.index, name='index'),
    # mostrar todos os assuntos
    path('topics/', views.topics, name='topics'),
    # Página de detalhes para um único assunto
    path('topics/<int:topic_id>', views.topic, name='topic'),
    # Página para adicionar um novo assunto
    path('new_topic/', views.new_topic, name='new_topic'),
    # Página para adicionar uma nova entrada
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    # Página para editar uma entrada
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Define padrões de URL para users."""

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
    # Pagina de login
    path('login/', LoginView.as_view(
        template_name='users/login.html'), name='login'),
    # Pagina de logout
    path('logout/', views.logout_view, name='logout'),
    # Página de cadastro
    path('register', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    """Um assunto sobre o qual o usuário esta aprendendo."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """Algo especificoaprendido sobre um assunto."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Metal:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Devolve uma representação em string do modelo."""
        return self.text if len(self.text) < 50 else f'{self.text[:50]}...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryFrom(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryFrom


# Create your views here.
def index(request):
    """A página inicial de learning Log"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Mostra todos os assuntos."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Mostra um único assunto e todas as suas entradas."""
    topic = get_object_or_404(Topic, id=topic_id)
    # Garante que o assunto pertence ao usuario atual
    check_topic_owner(request, topic)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Adiciona um novoassunto."""
    #  Nenhum dado submetido; cria um formulario em branco
    if request.method != 'POST':
        # Nenhum dado submetido; cria um formulário em branco
        form = TopicForm()
    else:
        # Dados de POST submetidos; processa os dados
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse_lazy('learning_logs:topics'))
    context = {'form': form}
    return render(
        request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Adiciona uma nova entrada para um assunto em particular."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # Nenhum dado submetido; cira um formulario em branco
        form = EntryFrom()
    else:
        # Dados de POST submetidos; processa os dados
        form = EntryFrom(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return HttpResponseRedirect(
                reverse_lazy('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edita uma entrada existente."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)

    if request.method != 'POST':
        # Reqquisição inicial; preenche previamente o formulário com a entrada
        # atual
        form = EntryFrom(instance=entry)
    else:
        # Dados de POST submetidos; processa os dados
        form = EntryFrom(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse_lazy('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


# Checa se os topicos pertence a um usuario.
@login_required
def check_topic_owner(request, topic):
    if topic.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def logout_view(request):
    """Faz logout do usuario."""
    logout(request)
    return HttpResponseRedirect(reverse_lazy('learning_logs:index'))


def register(request):
    """Faz o cadastro de um novo usuário."""
    if request.method != 'POST':
        # Exibe o formulario de cadastro em branco
        form = UserCreationForm()
    else:
        # Processa o formulario preenchido
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Faz login do usuário e o redireciona para a pagina inicial
            authenticate_user = authenticate(
                username=new_user.username, password=request.POST['password1'])
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse_lazy('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Registro de Aprendizado</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Registro de Aprendizado</a>  
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Assuntos</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Olá!, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">Sair</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">Registro</a></li>
                        <li><a href="{% url 'users:login' %}">Entrar</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.nav-collapse -->
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock %}
        </div>
        <div>
            {% block content %}{% endblock %}
        </div>
    </div> <!-- /container -->
  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
	
{% block header %}
	<h2>Editar entrada:</h2>
{% endblock %}

{% block content %}
	<h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
	<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST" class="form">
		{% csrf_token %}
			{% bootstrap_form form %}
		{% buttons %}
			<button name="submit" class="btn btn-primary">save changes</button>
		{% endbuttons %}
	</form>
{% endblock %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block header %}
	<dir class="jumbotron">
		<h1>Acompanhe seu aprendizado.</h1>
	</dir>
{% endblock %}

{% block content %}
		<h2>
			<a href="{% url 'users:register' %}">
			Ristre uma conta</a> para fazer seu próprio Registro de aprendizado e liste os assuntos sobre os quais você está aprendendo.
		</h2>
		<h2>
			Sempre que você aprender algo novo sobre um assunto, faça uma entrada resumindo o que você aprendeu.
		</h2>
{% endblock %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
	<h2>Adicione uma nova entrada:</h2>
{% endblock %}

{% block content %}
<h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST" class="form">
	{% csrf_token %}
		{% bootstrap_form form %}
	{% buttons %}
	<button name="submit" class="btn btn-primary">adicionar</button>
	{% endbuttons %}
</form>
{% endblock %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
	<h2>Adicione um novo assunto:</h2>
{% endblock %}

{% block content %}
	<form class="form" action="{% url 'learning_logs:new_topic' %}" method="POST">
		{% csrf_token %}
			{% bootstrap_form form %}
		{% buttons %}
			<button name="submit" class="btn btn-primary">Adicionar</button>
		{% endbuttons %}
	</form>
{% endblock %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

 {% block header %}
	<h1>{{ topic }}</h1>
{% endblock header %}


{% block content %}
	<p>
		<a href="{% url 'learning_logs:new_entry' topic.id %}">adicionar nova entrada</a>
	</p>
	{% for entry in entries %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>
					{{ entry.date_added|date:'M d, Y H:i' }}
					<small>
						<a href="{% url 'learning_logs:edit_entry' entry.id %}">Editar entrada</a>
					</small>
				</h3>
			</div>
			<div class="panel-body">
				{{ entry.text|linebreaks }}
			</div>
		</div> <!-- painel -->
	{% empty %}
		Ainda não há entradas para este assunto.
	{% endfor %}
{% endblock %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

 {% block header %}
	<h1>Assuntos</h1>
{% endblock header %}

{% block content %}
<ul>
	{% for topic in topics %}
		<li>
			<h3>
				<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
			</h3>
		</li>
	{% empty %}
		<li>Nenhum assunto foi adicionado.</li>
	{% endfor %}
</ul>
<h3><a href="{% url 'learning_logs:new_topic' %}">Adicionar novo assunto</a></h3>
{% endblock %}

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
	<h2>Faça login na sua conta.</h2>
{% endblock %}

{% block content %}

	<form class="form" action="{% url 'users:login' %}" method="POST">
		{% csrf_token %}
			{% bootstrap_form form %}

		{% buttons %}
		<button name="submit" class="btn btn-primary">Entrar</button>
		{% endbuttons %}
		<input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
	</form>
{% endblock %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
	<h2>Registrar uma conta:</h2>
{% endblock %}

{% block content %}
	<form action="{% url 'users:register' %}" method="POST" class="form">
		{% csrf_token %}
			{% bootstrap_form form %}
		{% buttons %}
		<button name="submit" class="btn btn-primary">Registrar</button>
		{% endbuttons %}
		<input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
	</form>
{% endblock %}